# -*- coding: utf-8 -*-
{
    'name': 'SGC TECH AI - Premium Theme',
    'version': '19.0.1.0.0',
    'category': 'Theme/Corporate',
    'summary': 'SGC TECH AI - sgctech.ai + store.sgctech.ai with AI Copilot',
    'description': """
SGC TECH AI Premium Odoo 19 Theme
=================================
Complete brand-aligned design system, AI Copilot, ROI Calculator,
eCommerce store, advanced login, mobile-first, WCAG AA, RTL ready.
    """,
    'author': 'SGC TECH AI - Scholarix Global Consultants',
    'website': 'https://sgctech.ai',
    'license': 'LGPL-3',
    'depends': [
        'base_setup', 'website', 'website_sale',
        'website_blog', 'website_slides', 'portal', 'mail', 'web', 'crm',
    ],
    'assets': {
        'web.assets_frontend': [
            'sgc_theme_ai/static/src/css/sgc_variables.css',
            'sgc_theme_ai/static/src/css/sgc_login.css',
            'sgc_theme_ai/static/src/css/sgc_base.css',
            'sgc_theme_ai/static/src/css/sgc_animations.css',
            'sgc_theme_ai/static/src/css/sgc_components.css',
            'sgc_theme_ai/static/src/css/sgc_website.css',
            'sgc_theme_ai/static/src/css/sgc_shop.css',
            'sgc_theme_ai/static/src/css/sgc_copilot.css',
            'sgc_theme_ai/static/src/css/sgc_responsive.css',
            'sgc_theme_ai/static/src/js/sgc_login.js',
            'sgc_theme_ai/static/src/js/sgc_core.js',
            'sgc_theme_ai/static/src/js/sgc_particles.js',
            'sgc_theme_ai/static/src/js/sgc_animations.js',
            'sgc_theme_ai/static/src/js/sgc_roi_calculator.js',
            'sgc_theme_ai/static/src/js/sgc_copilot.js',
            'sgc_theme_ai/static/src/js/sgc_website.js',
            'sgc_theme_ai/static/src/js/sgc_backdrop.js',
        ],
        'web.assets_backend': [
            'sgc_theme_ai/static/src/css/sgc_variables.css',
            'sgc_theme_ai/static/src/css/sgc_backend.css',
            'sgc_theme_ai/static/src/js/sgc_backend.js',
        ],
    },
    'data': [
        'security/ir.model.access.csv',
        'views/templates/layout.xml',
        'views/templates/header.xml',
        'views/templates/footer.xml',
        'views/templates/copilot.xml',
        'views/templates/homepage.xml',
        'views/templates/pricing.xml',
        'views/templates/about.xml',
        'views/templates/success_stories.xml',
        'views/templates/appointment.xml',
        'views/templates/real_estate.xml',
        'views/templates/solutions.xml',
        'views/templates/login.xml',
        'views/templates/portal.xml',
        'views/templates/shop.xml',
        'views/templates/snippets.xml',
    ],
    'images': ['static/description/banner.svg'],
    'post_init_hook': 'post_init_hook',
    'application': False,
    'installable': True,
    'auto_install': False,
}
