# Copyright 2025 SGC Tech AI
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).

import logging
import re

from odoo import _, api, fields, models
from odoo.exceptions import UserError

_logger = logging.getLogger(__name__)


class SGCMeetingNotes(models.Model):
    """AI-generated structured meeting notes.

    Produced by the LLM notes service. Posted to the calendar event's
    chatter and (optionally) emailed to attendees.
    """

    _name = "sgc.meeting.notes"
    _description = "SGC Meeting AI Notes"
    _inherit = ["mail.thread"]
    _order = "create_date desc"
    _rec_name = "display_name"

    display_name = fields.Char(compute="_compute_display_name", store=True)
    session_id = fields.Many2one(
        "sgc.meeting.session", required=True, ondelete="cascade", index=True
    )
    transcript_id = fields.Many2one(
        "sgc.meeting.transcript", string="Source Transcript", ondelete="set null"
    )
    provider_id = fields.Many2one(
        related="session_id.provider_id", string="Provider", store=True
    )
    summary = fields.Html(string="Summary", required=True)
    key_points = fields.Html(string="Key Discussion Points")
    decisions = fields.Html(string="Decisions Made")
    action_items = fields.Html(string="Action Items")
    risks = fields.Html(string="Risks & Blockers")
    model = fields.Char(string="LLM Model", help="LLM used for summarization.")
    tokens_used = fields.Integer()
    prompt_tokens = fields.Integer()
    completion_tokens = fields.Integer()
    posted_to_chatter = fields.Boolean(
        default=False,
        help="Whether the notes were posted to the meeting's chatter.",
    )
    emailed_to_attendees = fields.Boolean(
        default=False,
        help="Whether the notes were emailed to all attendees.",
    )
    gate_answers_draft = fields.Html(
        string="Gate Answers (Draft, from AI)",
        help="The 4 Verifiable Buyer Exit Criteria as extracted by the LLM "
        "from this meeting's transcript, when the meeting is linked to a "
        "CRM opportunity. A draft only — review before applying; nothing "
        "here counts as answered on the opportunity until "
        "'Apply to Opportunity' is clicked.",
    )
    # Discrete plain-text counterparts of gate_answers_draft, written by the
    # same summarize() call. The Html field above is for display in this
    # view; these are what action_apply_gate_answers_to_opportunity() copies
    # over, so applying never has to re-parse HTML back into text.
    gate_draft_problem = fields.Text(string="Draft: Problem")
    gate_draft_cost_of_inaction = fields.Text(string="Draft: Cost of Inaction")
    gate_draft_approver = fields.Text(string="Draft: Approver")
    gate_draft_timeline = fields.Text(string="Draft: Timeline")
    gate_answers_applied = fields.Boolean(
        default=False,
        help="Whether these draft gate answers have already been copied to "
        "the linked opportunity.",
    )
    opportunity_id = fields.Many2one(
        "crm.lead",
        string="Opportunity",
        related="session_id.meeting_id.opportunity_id",
        store=False,
        readonly=True,
    )

    @api.depends("session_id")
    def _compute_display_name(self):
        for notes in self:
            base = notes.session_id.name or _("Notes")
            stamp = (
                notes.create_date.strftime("%Y-%m-%d %H:%M")
                if notes.create_date
                else ""
            )
            notes.display_name = f"{base} — {stamp}" if stamp else base

    def action_post_to_chatter(self):
        """Post these notes as a message on the linked meeting's chatter."""
        self.ensure_one()
        if self.posted_to_chatter:
            return True
        body_parts = ["<h3>AI Meeting Notes</h3>", self.summary or ""]
        if self.key_points:
            body_parts.append("<h4>Key Points</h4>" + self.key_points)
        if self.decisions:
            body_parts.append("<h4>Decisions</h4>" + self.decisions)
        if self.action_items:
            body_parts.append("<h4>Action Items</h4>" + self.action_items)
        if self.risks:
            body_parts.append("<h4>Risks &amp; Blockers</h4>" + self.risks)
        body_parts.append(
            f"<p><small>Generated by SGC Meeting AI · model: {self.model or 'unknown'} · "
            f"tokens: {self.tokens_used or 0}</small></p>"
        )
        self.session_id.meeting_id.message_post(
            body="".join(body_parts),
            subject=_("AI Notes — %s", self.session_id.meeting_id.name or ""),
        )
        self.posted_to_chatter = True
        return True

    def action_apply_gate_answers_to_opportunity(self):
        """Open a review wizard for the 4 AI-drafted gate answers instead
        of copying them onto the opportunity directly (S1). An LLM
        inferring "who approves" from a transcript satisfies the field
        without satisfying the discipline the gate exists to enforce — the
        wizard shows each value as an editable, required field alongside
        the source transcript excerpt, so nothing counts as answered until
        a rep has actually reviewed (and, if needed, corrected) it.

        Requires sgc_sales_playbook to be installed (its x_gate_* fields on
        crm.lead). Checked at runtime via a plain field-existence lookup —
        not a model _inherit, so no manifest dependency is needed in this
        direction; sgc_sales_playbook depends on sgc_executive_dashboard,
        not the other way, and this module shouldn't have to depend on a
        sales-process module just to write 4 text fields when present.
        """
        self.ensure_one()
        if not self.opportunity_id:
            raise UserError(_("This meeting isn't linked to a CRM opportunity."))
        if "x_gate_problem" not in self.env["crm.lead"]._fields:
            raise UserError(
                _(
                    "The Sales Playbook module (sgc_sales_playbook) isn't "
                    "installed, so there's no gate to apply these answers to."
                )
            )
        return {
            "type": "ir.actions.act_window",
            "name": _("Review Gate Answers Before Applying"),
            "res_model": "sgc.gate.answers.apply.wizard",
            "view_mode": "form",
            "target": "new",
            "context": {"default_notes_id": self.id},
        }

    def action_email_attendees(self):
        """Email the notes summary to all attendees."""
        self.ensure_one()
        if not self.session_id.meeting_id.partner_ids:
            return False
        template = self.env.ref(
            "sgc_meeting_ai.email_template_meeting_notes", False
        )
        if not template:
            _logger.warning(
                "Missing email template sgc_meeting_ai.email_template_meeting_notes"
            )
            return False
        for partner in self.session_id.meeting_id.partner_ids:
            if not partner.email:
                continue
            template.send_mail(self.id, email_values={"recipient_ids": [(4, partner.id)]})
        self.emailed_to_attendees = True
        return True
