# Copyright 2025 SGC Tech AI
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).

import logging
import re

from odoo import _, api, fields, models

_logger = logging.getLogger(__name__)


class SGCMeetingNotes(models.Model):
    """AI-generated structured meeting notes.

    Produced by the LLM notes service. Posted to the calendar event's
    chatter and (optionally) emailed to attendees.
    """

    _name = "sgc.meeting.notes"
    _description = "SGC Meeting AI Notes"
    _inherit = ["mail.thread"]
    _order = "create_date desc"
    _rec_name = "display_name"

    display_name = fields.Char(compute="_compute_display_name", store=True)
    session_id = fields.Many2one(
        "sgc.meeting.session", required=True, ondelete="cascade", index=True
    )
    transcript_id = fields.Many2one(
        "sgc.meeting.transcript", string="Source Transcript", ondelete="set null"
    )
    provider_id = fields.Many2one(
        related="session_id.provider_id", string="Provider", store=True
    )
    summary = fields.Html(string="Summary", required=True)
    key_points = fields.Html(string="Key Discussion Points")
    decisions = fields.Html(string="Decisions Made")
    action_items = fields.Html(string="Action Items")
    risks = fields.Html(string="Risks & Blockers")
    model = fields.Char(string="LLM Model", help="LLM used for summarization.")
    tokens_used = fields.Integer()
    prompt_tokens = fields.Integer()
    completion_tokens = fields.Integer()
    posted_to_chatter = fields.Boolean(
        default=False,
        help="Whether the notes were posted to the meeting's chatter.",
    )
    emailed_to_attendees = fields.Boolean(
        default=False,
        help="Whether the notes were emailed to all attendees.",
    )

    @api.depends("session_id")
    def _compute_display_name(self):
        for notes in self:
            base = notes.session_id.name or _("Notes")
            stamp = (
                notes.create_date.strftime("%Y-%m-%d %H:%M")
                if notes.create_date
                else ""
            )
            notes.display_name = f"{base} — {stamp}" if stamp else base

    def action_post_to_chatter(self):
        """Post these notes as a message on the linked meeting's chatter."""
        self.ensure_one()
        if self.posted_to_chatter:
            return True
        body_parts = ["<h3>AI Meeting Notes</h3>", self.summary or ""]
        if self.key_points:
            body_parts.append("<h4>Key Points</h4>" + self.key_points)
        if self.decisions:
            body_parts.append("<h4>Decisions</h4>" + self.decisions)
        if self.action_items:
            body_parts.append("<h4>Action Items</h4>" + self.action_items)
        if self.risks:
            body_parts.append("<h4>Risks &amp; Blockers</h4>" + self.risks)
        body_parts.append(
            f"<p><small>Generated by SGC Meeting AI · model: {self.model or 'unknown'} · "
            f"tokens: {self.tokens_used or 0}</small></p>"
        )
        self.session_id.meeting_id.message_post(
            body="".join(body_parts),
            subject=_("AI Notes — %s", self.session_id.meeting_id.name or ""),
        )
        self.posted_to_chatter = True
        return True

    def action_email_attendees(self):
        """Email the notes summary to all attendees."""
        self.ensure_one()
        if not self.session_id.meeting_id.partner_ids:
            return False
        template = self.env.ref(
            "sgc_meeting_ai.email_template_meeting_notes", False
        )
        if not template:
            _logger.warning(
                "Missing email template sgc_meeting_ai.email_template_meeting_notes"
            )
            return False
        for partner in self.session_id.meeting_id.partner_ids:
            if not partner.email:
                continue
            template.send_mail(self.id, email_values={"recipient_ids": [(4, partner.id)]})
        self.emailed_to_attendees = True
        return True
