{
    "name": "SGC - Payment Management",
    "version": "19.0.1.0.0",
    "category": "Accounting/Payments",
    "summary": "Extended payment workflows, approval stages, QR verification, and dashboard",
    "author": "SmartClinic",
    "website": "https://sgctech.ai",
    "license": "LGPL-3",
    "depends": ["base", "account", "mail", "account_payment"],
    "data": [
        "security/groups.xml",
        "security/ir.model.access.csv",
        "views/account_move_views.xml",
        "views/payment_approval_history_views.xml",
        "views/payment_dashboard_views.xml",
        "views/payment_qr_verification_views.xml",
        "views/payment_workflow_stage_views.xml",
        "views/executive_views.xml",
        "views/menus.xml",
    ],
    "installable": True,
    "application": False,
    "auto_install": False,
}
