# -*- coding: utf-8 -*-
{
    'name': 'SGC Tech AI — v2026 Website',
    'version': '19.0.1.0.0',
    'category': 'Website/Theme',
    'summary': 'Premium Odoo 19 website for SGC Tech AI — UAE B2B ERP, v2026.05 doctrine.',
    'description': 'Seven fully-designed, compliance-correct pages for scholarixglobal.com and sgctech.ai.',
    'author': 'SGC Tech AI',
    'website': 'https://sgctech.ai',
    'license': 'LGPL-3',
    'depends': ['website', 'website_sale', 'crm', 'auth_signup', 'base_setup'],
    'data': [
        'views/layout.xml',
        'views/home.xml',
        'views/pricing.xml',
        'views/industries.xml',
        'views/how_we_work.xml',
        'views/compliance.xml',
        'views/about.xml',
        'views/contact.xml',
        'views/brand_promotion.xml',
        'views/snippets/sgc_snippets.xml',
        'data/pages.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            'sgctech_ai_2026/static/src/css/01_variables.css',
            'sgctech_ai_2026/static/src/css/02_base.css',
            'sgctech_ai_2026/static/src/css/03_layout.css',
            'sgctech_ai_2026/static/src/css/04_typography.css',
            'sgctech_ai_2026/static/src/css/05_buttons.css',
            'sgctech_ai_2026/static/src/css/13_no_odoo.css',
            'sgctech_ai_2026/static/src/css/06_cards.css',
            'sgctech_ai_2026/static/src/css/07_hero.css',
            'sgctech_ai_2026/static/src/css/08_pricing.css',
            'sgctech_ai_2026/static/src/css/09_industries.css',
            'sgctech_ai_2026/static/src/css/10_compliance.css',
            'sgctech_ai_2026/static/src/css/11_animations.css',
            'sgctech_ai_2026/static/src/css/12_responsive.css',
            'sgctech_ai_2026/static/src/js/sgc26_core.js',
            'sgctech_ai_2026/static/src/js/sgc26_particles.js',
            'sgctech_ai_2026/static/src/js/sgc26_reveal.js',
            'sgctech_ai_2026/static/src/js/sgc26_countup.js',
            'sgctech_ai_2026/static/src/js/sgc26_tilt.js',
            'sgctech_ai_2026/static/src/js/sgc26_contact.js',
        ],
    },
    'installable': True,
    'auto_install': False,
    'application': False,
}
