{
    "name": "SGC Aurum Theme",
    "summary": "Navy & gold Aurum theme for SGC Tech backend and website",
    "version": "19.0.2.0.2",
    "category": "Theme/Corporate",
    "author": "SGC Tech",
    "license": "LGPL-3",
    "depends": ["website", "web"],
    "data": [
        "views/website_page.xml",
        "views/website_page_about.xml",
        "views/website_page_services.xml",
        "views/website_page_industries.xml",
        "views/website_page_approach.xml",
        "views/website_page_pricing.xml",
        "views/website_page_contact.xml",
        "views/website_page_data.xml",
        "views/aurum_fonts.xml",
        "views/aurum_accessibility.xml",
        "views/aurum_layout.xml",
        "views/auth_templates.xml",
        "views/ir_asset.xml",
    ],
    "post_init_hook": "post_init_hook",
    "installable": True,
    "application": False,
}
